# -*- coding: utf-8 -*-
"""ToolRegistry — Single source of truth for tool metadata.

Each tool declares on registration:
    - Type (file / network / shell / internal)
    - Target parameter name (file_path / command / url …)
    - Python function name → policy tool name mapping

Relationship with policy.yaml:
    ToolRegistry: what a tool is (type, parameter name)
        → static, registered in code
    policy.yaml:  what a tool can do (rules, default perms)
        → dynamic, generated by user/approve
"""

from __future__ import annotations
import os
from typing import Any, Dict, List


class ToolRegistry:
    """Tool metadata registry."""

    def __init__(self) -> None:
        self._types: Dict[str, str] = {}
        self._target_params: Dict[str, str] = {}
        self._python_name_map: Dict[str, str] = {}
        # Tools whose target should combine path + pattern
        # (e.g. Glob: pattern is a file glob, so path+pattern
        # forms a complete filesystem path pattern for rule matching).
        self._pattern_params: Dict[str, str] = {}
        # Tools that refuse to run (fail closed) unless a sandbox_config is
        # supplied — as opposed to shell tools like Bash that execute directly
        # when unsandboxed. See ``requires_sandbox`` for why this matters.
        self._sandbox_required: Dict[str, bool] = {}

    def register(
        self,
        tool_name: str,
        tool_type: str,
        target_param: str,
        pattern_param: str = "",
        sandbox_required: bool = False,
    ) -> None:
        """Register a tool.

        Args:
            tool_name: policy-layer tool name, e.g. "Read"
            tool_type: "file" | "network" | "shell" | "internal"
            target_param: target parameter name, e.g. "file_path", "command"
            pattern_param: for file-search tools (e.g. Glob), the parameter
                name holding the glob pattern. When set, ``extract_target``
                combines path + pattern into a single filesystem path pattern.
            sandbox_required: ``True`` for tools that **fail closed** without a
                ``sandbox_config`` (e.g. ``recall_history_python``, which runs
                model-authored Python and returns ``DENIED`` when no sandbox is
                supplied). Distinct from mere shell-type: ``Bash`` is shell but
                fail-*open* — it executes unsandboxed when no config is given.
                Consumed by the approval_level=OFF path, which must still
                compile a sandbox for these tools instead of letting them dead
                -end in a sandbox-violation → approval loop.
        """
        self._types[tool_name] = tool_type
        self._target_params[tool_name] = target_param
        if pattern_param:
            self._pattern_params[tool_name] = pattern_param
        if sandbox_required:
            self._sandbox_required[tool_name] = True

    def register_python_name(self, python_name: str, policy_name: str) -> None:
        """Register a python function name → policy tool name mapping."""
        self._python_name_map[python_name] = policy_name

    def get_type(self, tool_name: str) -> str:
        """Return the tool's type. Returns "unknown" if not registered."""
        return self._types.get(tool_name, "unknown")

    def get_target_param(self, tool_name: str) -> str:
        """Return the tool's target parameter name.

        Returns "" if not registered.
        """
        return self._target_params.get(tool_name, "")

    def requires_sandbox(self, tool_name: str) -> bool:
        """Whether the tool fails closed without a ``sandbox_config``.

        ``True`` only for tools that refuse to run unsandboxed (the REPL).
        Returns ``False`` for unregistered tools and for fail-open shell
        tools like ``Bash`` that execute directly when no sandbox is given.
        """
        return self._sandbox_required.get(tool_name, False)

    def python_to_policy_name(self, python_name: str) -> str:
        """Map a python function name to a policy tool name.

        Checks explicit mapping first; if no mapping exists, converts
        snake_case → PascalCase.
        """
        override = self._python_name_map.get(python_name)
        if override:
            return override
        parts = python_name.split("_")
        return "".join(p.capitalize() for p in parts)

    def extract_target(
        self,
        tool_name: str,
        input_data: dict[str, Any],
        workspace_dir: str = "",
    ) -> str:
        """Extract the target from tool call arguments."""
        param = self.get_target_param(tool_name)
        if not param:
            return ""

        # 1) Get base path from input
        path = input_data.get(param, "")
        path = str(path) if path else ""

        # Expand a leading ``~`` to the user's home directory
        if path:
            path = os.path.expanduser(path)

        # 2) For file tools, resolve empty/relative path using workspace_dir
        if self._types.get(tool_name) == "file" and workspace_dir:
            if not path:
                path = workspace_dir
            elif not os.path.isabs(path):
                path = os.path.join(workspace_dir, path)

        # 3) Append pattern for file-search tools (e.g. Glob)
        pattern_param = self._pattern_params.get(tool_name)
        if pattern_param:
            pattern = input_data.get(pattern_param, "")
            if pattern:
                path = (
                    os.path.join(path, str(pattern)) if path else str(pattern)
                )

        return path

    def get_all_tool_names(self) -> List[str]:
        """Return all registered tool names."""
        return list(self._types.keys())


# ---------------------------------------------------------------------------
# Default registry instance (21 tools)
# ---------------------------------------------------------------------------


def _create_default_registry() -> ToolRegistry:
    """Create and populate the default ToolRegistry."""
    registry = ToolRegistry()
    _register_builtin_tools(registry)
    _register_python_name_mappings(registry)
    return registry


def _register_builtin_tools(r: ToolRegistry) -> None:
    """Register all built-in tool types."""
    # ── File tools ──
    for name, param in [
        ("Read", "file_path"),
        ("Write", "file_path"),
        ("Edit", "file_path"),
        ("Append", "file_path"),
        ("Grep", "path"),
        ("SendFileToUser", "file_path"),
        ("ViewImage", "image_path"),
        ("ViewVideo", "video_path"),
        ("DesktopScreenshot", "path"),
        ("SetUserTimezone", "timezone"),
    ]:
        r.register(name, "file", param)
    r.register("Glob", "file", "path", pattern_param="pattern")

    # ── Network / Shell ──
    r.register("Browser", "network", "url")
    r.register("Bash", "shell", "command")
    # Fail-closed: the REPL runs model-authored Python and returns DENIED
    # unless a sandbox_config is supplied (unlike Bash, which is fail-open).
    r.register("RecallHistoryPython", "shell", "source", sandbox_required=True)
    # Structured recall: bound-parameter read-only queries over history.db —
    # the model supplies scalars, never code, so no sandbox/approval needed.
    r.register("RecallHistory", "internal", "op")

    # ── Internal tools ──
    for name, param in [
        ("GetCurrentTime", ""),
        ("GetTokenUsage", ""),
        ("ListAgents", ""),
        ("MaterializeSkill", ""),
        ("ChatWithAgent", "agent_id"),
        ("SubmitToAgent", "agent_id"),
        ("CheckAgentTask", "task_id"),
        ("SpawnSubagent", ""),
        ("DelegateExternalAgent", "runner"),
        ("MemorySearch", ""),
    ]:
        r.register(name, "internal", param)


def _register_python_name_mappings(
    r: ToolRegistry,
) -> None:
    """Register python func name → policy name maps."""
    mappings = {
        "execute_shell_command": "Bash",
        "read_file": "Read",
        "write_file": "Write",
        "edit_file": "Edit",
        "memory_search": "MemorySearch",
        "append_file": "Append",
        "grep_search": "Grep",
        "glob_search": "Glob",
        "browser_use": "Browser",
        "desktop_screenshot": "DesktopScreenshot",
        "send_file_to_user": "SendFileToUser",
        "view_image": "ViewImage",
        "view_video": "ViewVideo",
        "get_current_time": "GetCurrentTime",
        "set_user_timezone": "SetUserTimezone",
        "get_token_usage": "GetTokenUsage",
        "delegate_external_agent": "DelegateExternalAgent",
        "list_agents": "ListAgents",
        "chat_with_agent": "ChatWithAgent",
        "submit_to_agent": "SubmitToAgent",
        "check_agent_task": "CheckAgentTask",
        "spawn_subagent": "SpawnSubagent",
        "materialize_skill": "MaterializeSkill",
    }
    for py_name, policy_name in mappings.items():
        r.register_python_name(py_name, policy_name)


DEFAULT_REGISTRY = _create_default_registry()
